# Generated by Django 3.0.4 on 2020-03-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('apiname', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('apiname', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
    ]
